parameters:
    key_name:
        type: string
        description: Keypair name
    net_name:
        type: string
        description: Net name
heat_template_version: 2017-02-24
description: Database
resources: 
    db:
        type: OS::Nova::Server
        properties:
            key_name: { get_resource: server_ssh_key }
            image:  db-image
            flavor: m1.smaller
            networks:
                - network: { get_param: net_name }
            user_data_format: SOFTWARE_CONFIG
            user_data:
                str_replace:
                    template: {get_file: mongo-start.sh}
                    params:
                        $VMNAME: {get_param: key_name}
    server_ssh_key:
        type: OS::Nova::KeyPair
        properties:
            name: { get_param: key_name }
            save_private_key: true
            
outputs:
    instance_ip:
        description: The IP address of the deployed instance
        value: { get_attr: [db, first_address] }
