parameters:
    net_name1:
        type: string
        description: Net name 1
    net_name2:
        type: string
        description: Net name 2
heat_template_version: 2017-02-24
description: Ejemplo1,una maquina virtual CirrOS con red
resources: 
    vmtest:
        type: OS::Nova::Server
        properties:
            image: xenial-server-cloudimg-amd64-vnx
            flavor: m1.smaller
            networks:
                - network: { get_param: net_name1 }
                - network: { get_param: net_name2 }
outputs:
    instance_ip:
        description: The IP address of the deployed instance
        value: { get_attr: [vmtest, networks, net1, 0] }
