parameters:
    net_name:
        type: string
        description: Net name
heat_template_version: 2017-02-24
description: Firewall
resources: 
    fw:
        type: OS::Neutron::Firewall
        properties:
            name: firewall
            admin_state_up: true
            firewall_policy_id: { get_resource: firewall_policy_id }
            networks:
                - network: { get_param: net_name }
    firewall_policy_id:
        type: OS::Neutron::FirewallPolicy
        properties:
            name: fw_policy_1
            firewall_rules: [ { get_resource: firewall_rule_tcp } ]
    firewall_rule_tcp:
        type: OS::Neutron::FirewallRule
        properties:
            name: tcp_http
            description: TCP/HTTP traffic management
            action: allow
            protocol: tcp
            destination_port: 80
            enabled: true
outputs:
    instance_ip:
        description: The IP address of the deployed instance
        value: { get_attr: [fw, first_address] }
