parameters:
    key_name:
        type: string
        description: Keypair name
    net_name1:
        type: string
        description: Net name
    net_name2:
        type: string
        description: Net name
heat_template_version: 2017-02-24
description: Ejemplo1,una maquina virtual CirrOS sin red
resources: 
    vm:
        type: OS::Nova::Server
        properties:
            key_name: { get_resource: server_ssh_key }
            image:  xenial-server-cloudimg-amd64-vnx
            flavor: m1.smaller
            networks:
                - network: { get_param: net_name2 }
                - network: { get_param: net_name1 }
    server_ssh_key:
        type: OS::Nova::KeyPair
        properties:
            name: { get_param: key_name }
            save_private_key: true
outputs:
    instance_ip:
        description: The IP address of the deployed instance
        value: { get_attr: [vm, networks, net1, 0] }
